Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [6]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Yes,there is a difference between the data type of variables "list_" & "array_list".
"list_" variables contains the data type : Python Strings whereas "array_list" datasets contains data type :
array.strings 

### Code to check the data type 

In [11]:
print("Type of list_:",type(list_))
print("Type of array_list:",type(array_list))

Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [19]:
#priniting data type of each and every element in list_ 

for i in list_:
    print(f"Value of Element : {i} and data of Element : {type(i)}")
    

Value of Element : 1 and data of Element : <class 'str'>
Value of Element : 2 and data of Element : <class 'str'>
Value of Element : 3 and data of Element : <class 'str'>
Value of Element : 4 and data of Element : <class 'str'>
Value of Element : 5 and data of Element : <class 'str'>


In [21]:
#priniting data type of each and every element in array_list:

for i in array_list:
    print(f"Value of Element : {i} and data of Element : {type(i)}")

Value of Element : 1 and data of Element : <class 'numpy.str_'>
Value of Element : 2 and data of Element : <class 'numpy.str_'>
Value of Element : 3 and data of Element : <class 'numpy.str_'>
Value of Element : 4 and data of Element : <class 'numpy.str_'>
Value of Element : 5 and data of Element : <class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Yes,there is a difference between the data type of variables "list_" & "array_list".
"list_" variables contains the data type : Python Strings whereas "array_list" datasets contains data type :
numpy.integer 

In [22]:
array_list = np.array(object = list_, dtype = int)

In [23]:
##viewing the array
array_list

array([1, 2, 3, 4, 5])

In [24]:
#priniting data type of each and every element in list_ 

for i in list_:
    print(f"Value of Element : {i} and data of Element : {type(i)}")

Value of Element : 1 and data of Element : <class 'str'>
Value of Element : 2 and data of Element : <class 'str'>
Value of Element : 3 and data of Element : <class 'str'>
Value of Element : 4 and data of Element : <class 'str'>
Value of Element : 5 and data of Element : <class 'str'>


In [26]:
#priniting data type of each and every element in array_list:

for i in array_list:
    print(f"Value of Element : {i} and data of Element : {type(i)}")

Value of Element : 1 and data of Element : <class 'numpy.int32'>
Value of Element : 2 and data of Element : <class 'numpy.int32'>
Value of Element : 3 and data of Element : <class 'numpy.int32'>
Value of Element : 4 and data of Element : <class 'numpy.int32'>
Value of Element : 5 and data of Element : <class 'numpy.int32'>


## Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [28]:
#Given list
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [32]:
#viewing array 
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

### Q4. Write a code to find the following characteristics of variable, num_array:
    (i) shape
    (ii) size

### Characteristics of variable, num_array:

In [35]:
#Shape 
print(f"Shape of num_array : {num_array.shape}")
#Size 
print(f"\nSize of num_array : {num_array.size}")

Shape of num_array : (2, 3)

Size of num_array : 6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

## [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?
## [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [41]:
identity_mat=np.eye(5,5)

In [42]:
identity_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])